fix: fetch superset info from oauth
openedx/tutor-contrib-superset pull request #44
Opened 2023-05-29 15:49 UTC by Ian2012

## Description

This PR updates the oauth implementation to get a JWT to get the user information.

Have in mind that edx-platform doesn't store the fields first name and last name, that's why we need to provide the name base on the full name field. In the screenshot below, the user **Cristhian G** was logged in with the new implementation.
![image](https://github.com/openedx/tutor-contrib-superset/assets/33465240/76c8a87f-728a-471c-bee7-b881f6ab5ce4)

Also, the current implementation doesn't update the name after following logins.

## Fixed issues:

- https://github.com/openedx/openedx-oars/issues/42
- https://github.com/openedx/tutor-contrib-superset/issues/11

2023-05-29 15:49 UTC, openedx-webhooks commented
Thanks for the pull request, @Ian2012!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-05-30 00:01 UTC, mariajgrimaldi requested changes

2023-05-30 00:01 UTC, mariajgrimaldi commented on tutorsuperset/templates/superset/apps/pythonpath/superset_config_docker.py
> +                'token_type': 'jwt'
I'd like to try testing this out without specifying the token type, just adding the SIGN_METHOD

2023-05-30 00:03 UTC, mariajgrimaldi commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> +from authlib.integrations.flask_client.apps import FlaskOAuth2App
There are a lot of imports that are not being used, can you remove them? Thanks!

2023-05-30 00:03 UTC, mariajgrimaldi commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> +from authlib.integrations.flask_client.apps import FlaskOAuth2App
Can you also run isort?

2023-05-30 01:23 UTC, mariajgrimaldi commented
I tested this and it's working as expected. Just one quick comment, the first name and last name are recorded after registering, if the user already exists, then it's not saved again. I didn't know that. Maybe there's a configuration for updating existing users -- maybe it's not even needed since this project is brand new.

2023-05-30 01:44 UTC, Ian2012 commented on tutorsuperset/templates/superset/apps/pythonpath/superset_config_docker.py
> +                'token_type': 'jwt'
It doesn't work. It's a parameter needed by the openedx api, but we can test it out

2023-05-30 02:19 UTC, mariajgrimaldi commented on tutorsuperset/templates/superset/apps/pythonpath/superset_config_docker.py
> +                'token_type': 'jwt'
I remember now

2023-05-31 04:38 UTC, pomegranited requested changes
This is looking fantastic, and really close to being done! Great work @Ian2012 and @mariajgrimaldi , this is so much cleaner.

Please see comments inline.

2023-05-31 04:38 UTC, pomegranited commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> -    openedx_database = current_app.config['OPENEDX_DATABASE']
We can delete the [`OPENEDX_DATABASE` config](https://github.com/openedx/tutor-contrib-superset/blob/94c066a0c6b56afd071ae49ca549ba4d71044708/tutorsuperset/templates/superset/apps/pythonpath/superset_config_docker.py#L14-L20) and its [related env variables](https://github.com/search?q=repo%3Aopenedx%2Ftutor-contrib-superset%20OPENEDX_MYSQL_&type=code) too, yay!

2023-05-31 04:38 UTC, pomegranited commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> +            session["oauth_token"] = oauth_response["access_token"]
This change and the [related one below](https://github.com/openedx/tutor-contrib-superset/pull/44/files#diff-86883c60f8e1c94fe60abff51337290ebb6d04e9fac49f8c6731d7613045f445L60) need to be rolled back:

```suggestion
            session["oauth_token"] = oauth_response
```

Without these fixes, when I try to login to Superset as a non-staff, non-superuser using this code, I get through the Open edX OAuth permission screen, but then Superset  says "Invalid login. Please try again. "
This error doesn't occur for users with `is_superuser=True` or `is_staff=True`, they both login fine, so maybe it's related to FAB's roles checks? I don't know.

Logs show this ERROR:

```
superset_1                   | 172.26.0.1 - - [31/May/2023:03:38:58 +0000] "GET /login/openedxsso?next= HTTP/1.1" 302 866 "http://superset.local.overhang.io:8088/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0"
superset_1                   | 2023-05-31 03:39:02,501:ERROR:flask_appbuilder.security.views:Error returning OAuth user info: 'str' object has no attribute 'is_expired'
superset_1                   | 172.26.0.1 - - [31/May/2023:03:39:02 +0000] "GET /oauth-authorized/openedxsso?code=ILqbV3cF9LZmv44icvQEbqRT6gxczv&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuZXh0IjpbIiJdfQ.G8JbeDwJwoZpkdiwXwMQdznT76FDW6qXn_Ym3Lg9OAk HTTP/1.1" 302 220 "http://superset.local.overhang.io:8088/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0"
```

2023-05-31 04:38 UTC, pomegranited commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> +        return self.get_oauth_token()
Please revert this as [described above](https://github.com/openedx/tutor-contrib-superset/pull/44/files#diff-86883c60f8e1c94fe60abff51337290ebb6d04e9fac49f8c6731d7613045f445R86):

```suggestion
        return self.get_oauth_token().get('access_token')
```

2023-05-31 04:38 UTC, pomegranited commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> +                'last_name': user_profile['given_name'],
Confirmed the issue @mariajgrimaldi noted above.. 
And I think it would be safer to use `user_profile.get` with sensible defaults everywhere of risking `KeyError`s?

```suggestion
                'first_name': user_profile.get('given_name', user_profile.get('name', '')),
                'last_name': user_profile.get('family_name'),
```

2023-06-01 16:17 UTC, Ian2012 commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> +            user_profile = self.decoded_user_info()
@pomegranited can you try again?

I refactored the code and I think is resolved. I just tested with a non-staff non-superuser user and it works

2023-06-01 21:10 UTC, mariajgrimaldi commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
can we run isort?

2023-06-01 21:10 UTC, mariajgrimaldi commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> +def add_bearer_jwt_token(token, uri, headers, body, placement='header'):
can we add docstrings here?

2023-06-02 15:22 UTC, Ian2012 commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
done

2023-06-02 15:22 UTC, Ian2012 commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> +def add_bearer_jwt_token(token, uri, headers, body, placement='header'):
done

2023-06-02 15:28 UTC, mariajgrimaldi approved these changes
I tested this deployed in one of our installations, and it's working nicely! Thank you for the improvement 🥳

2023-06-05 09:19 UTC, pomegranited commented on tutorsuperset/templates/superset/apps/pythonpath/openedx_sso_security_manager.py
> +                'first_name': user_profile.get('given_name', user_profile.get('name', '')),
My mistake, this doesn't work, because usually `user_profile['given_name'] == ''`.
Will have to be:
```suggestion
                'first_name': user_profile.get('given_name') || user_profile.get('name', ''),
```

2023-06-05 09:23 UTC, pomegranited approved these changes
:+1: This works perfectly @Ian2012 ! Couple of minor nits noted below, but it's good to merge when they're resolved.

- [x] I tested this on a fresh Tutor dev deployment.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation</strike> N/A

2023-06-05 18:31 UTC, merged

2023-06-05 18:31 UTC, openedx-webhooks commented
@Ian2012 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-superset&entry.867055334=https://github.com/openedx/tutor-contrib-superset/pull/44&entry.1484655318=https://github.com/Ian2012&entry.752974735=2023-05-29+15:49&entry.1917517419=2023-06-05+18:31&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->